# Source: https://hub.docker.com/_/mysql
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=cndb
      - MYSQL_USER=cnuser
      - MYSQL_PASSWORD=cnpass
      - MYSQL_ROOT_PASSWORD=cnrootpass
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
